//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fsAccount()
        {
            this.fsTrxDetails = new HashSet<fsTrxDetail>();
            this.fsSubAccnts = new HashSet<fsSubAccnt>();
        }
    
        public int Id { get; set; }
        public string AccntNo { get; set; }
        public string AccntTitle { get; set; }
        public string Description { get; set; }
        public string IncreaseCode { get; set; }
        public int fsAccntCategoryId { get; set; }
    
        public virtual fsAccntCategory fsAccntCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fsTrxDetail> fsTrxDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fsSubAccnt> fsSubAccnts { get; set; }
    }
}
