//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsEntityUsers
    {
        public int Id { get; set; }
        public int fsEntityId { get; set; }
        public int fsUserId { get; set; }
        public int isAdmin { get; set; }
    
        public virtual fsEntity fsEntity { get; set; }
        public virtual fsUser fsUser { get; set; }
    }
}
