//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsRptCatAccnt
    {
        public int Id { get; set; }
        public int fsAccountId { get; set; }
        public int fsRptCatId { get; set; }
        public int Sort { get; set; }
    
        public virtual fsAccount fsAccount { get; set; }
        public virtual fsRptCat fsRptCat { get; set; }
    }
}
