//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsTrxHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fsTrxHdr()
        {
            this.fsTrxDetails = new HashSet<fsTrxDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtTrx { get; set; }
        public string Status { get; set; }
        public string trxRemarks { get; set; }
        public string dtEntry { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> dtEdit { get; set; }
        public string EditedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fsTrxDetail> fsTrxDetails { get; set; }
    }
}
