//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsTrxDetail
    {
        public int Id { get; set; }
        public int fsTrxHdrId { get; set; }
        public int fsAccountId { get; set; }
        public Nullable<int> fsSubAccntId { get; set; }
        public string Description { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
    
        public virtual fsAccount fsAccount { get; set; }
        public virtual fsTrxHdr fsTrxHdr { get; set; }
        public virtual fsSubAccnt fsSubAccnt { get; set; }
    }
}
